Added Ingress and Egress Rules for Standard and Dry Run
terraform-google-modules/terraform-google-vpc-service-controls pull request #55
Opened 2021-08-31 08:09 UTC by aweberlopes

Hello Guys,

i added my code and checked the Contributing Guidelines. The tests are unsuccessful because the new blocks are not implemented on the tests. 

I tested the VPC SC in a Demo Organization and mostly functions work similar like on the ressource. 

Please be kindly its my first pull request on GitHub so maybe i missing something.

2021-08-31 08:21 UTC, aweberlopes commented
@googlebot I signed it!

2021-08-31 10:48 UTC, aweberlopes commented
@morgante Can you provide me the info where the Cloud Build Job fails that i can fix the issue
I can not test it localy in my env because i can not delete access policy it would delete all existing perimeter.

2021-09-20 12:58 UTC, aweberlopes commented
Hello together is here happening something?

2021-09-20 14:09 UTC, morgante commented
Hi this is is the test failure:
```
       module.example.module.access_context_manager_policy.google_access_context_manager_access_policy.access_policy: Destroying... [id=580200975946]
       module.example.module.access_context_manager_policy.google_access_context_manager_access_policy.access_policy: Destruction complete after 1s
       
       Error: cannot destroy instance without setting deletion_protection=false and running `terraform apply`
       
```

2021-09-24 11:07 UTC, aweberlopes commented
So tests are successful. Can somebody have a look on it?

2021-09-29 06:27 UTC, aweberlopes commented
@morgante Is something missing here?

2021-09-29 17:00 UTC, morgante requested changes
Thank you for contributing! This looks quite helpful.

Please also add these values to an example.

2021-09-29 18:34 UTC, aweberlopes commented
will fix the rest tomorrow @morgante thanks for the sugesstions and fixes

2021-09-30 08:50 UTC, aweberlopes commented
@morgante so simplified it can you check again?

2021-09-30 14:32 UTC, morgante requested changes
Thanks for cleaning up some of the examples. Please also add ingress and egress policies to an example+cloud to verify it's behaving correctly—right now the conditional logic looks intercorrect.

2021-09-30 14:32 UTC, morgante commented on modules/regular_service_perimeter/main.tf
> +          identity_type = lookup(ingress_policies.value["from"], "identity_type", lookup(ingress_policies.value["from"], "identities", "ANY_IDENTITY")) ? "" : null
It looks like this value will never end up being set, due to the ternary.

2021-09-30 14:32 UTC, morgante commented on modules/regular_service_perimeter/main.tf
> +          identities    = lookup(ingress_policies.value["from"], "identity_type", lookup(ingress_policies.value["from"], "identities", [])) ? [] : null
This conditional isn't quite right.

2021-09-30 16:17 UTC, aweberlopes commented
Okay will have a look thanks.

2021-10-01 09:56 UTC, bchazalet commented
this looks useful. I'll definitely try it out once released.

2021-10-05 10:30 UTC, bchazalet commented
i've been testing this branch with success on a project of mine

2021-10-05 14:16 UTC, morgante approved these changes

2021-10-05 14:17 UTC, merged